import User from "../../models/User.js";
import { enqueueTelegramNotification } from "./telegramQueueService.js";

// =====================================================
// SEND CHART WATCH TELEGRAM ALERT
// =====================================================

export async function notifyTelegramChartWatch(
  watch,
  result
) {
  try {

    // ============================================
    // Validate watch
    // ============================================

    if (!watch?.walletAddress) {
      return;
    }

    // ============================================
    // Find user
    // ============================================

    const user = await User.findOne({
      walletAddress: watch.walletAddress,
    }).lean();

    if (!user) {
      return;
    }

    // ============================================
    // Telegram not linked
    // ============================================

    if (!user.telegram?.userId) {
      return;
    }

    // ============================================
    // Build message
    // ============================================

    const message = buildTelegramMessage(
      watch,
      result
    );

    // ============================================
    // Queue Telegram notification
    // ============================================

    await enqueueTelegramNotification({
      telegramUserId: user.telegram.userId,
      message,
      parseMode: "HTML",
    });

    console.log(
      `📨 Telegram notification queued for ${user.telegram.userId}`
    );

  } catch (err) {

    console.error(
      "❌ Failed to queue Telegram notification:",
      err.message
    );

  }
}

// =====================================================
// BUILD TELEGRAM MESSAGE
// =====================================================

function buildTelegramMessage(
  watch,
  result
) {

  const analysis =
    result.analysis || {};

  const symbol =
    watch.tokenSymbol || "Unknown";

  const forecast =
    watch.forecastScore ?? "-";

  return `
📈 <b>Chart Watch Update</b>

🪙 <b>Token:</b> ${symbol}

📊 <b>Event:</b> ${result.event}

⏮ <b>Previous:</b> ${result.previousAction}

▶️ <b>Current:</b> ${result.currentAction}

🎯 <b>Forecast Score:</b> ${forecast}

🔥 <b>Confidence:</b> ${analysis.confidence ?? "-"}

💰 <b>Entry Zone:</b>
${analysis.entryMin ?? "-"} - ${analysis.entryMax ?? "-"}

🎯 <b>Take Profit:</b>
${analysis.takeProfitLevel ?? "-"}

🛑 <b>Invalidation:</b>
${analysis.invalidationLevel ?? "-"}

📌 <b>Recommended Action:</b>
${analysis.action ?? "-"}

🤖 <i>Generated by Autoswaps AI Chart Monitor</i>
`;

}