import { createNotification } from "./notificationService.js";
import User from "../../models/User.js";
import bot from "../telegram/bot.js";

// =====================================================
// BUILD NOTIFICATION
// =====================================================

function buildNotification(result, watch) {
  switch (result.event) {
    case "BREAKOUT_CONFIRMED":
      return {
        type: "success",
        title: "🚀 Breakout Confirmed",
        message: `${watch.symbol || "Token"} has confirmed its breakout. Entry conditions have been met.`,
      };

    case "PULLBACK_COMPLETED":
      return {
        type: "success",
        title: "📈 Pullback Complete",
        message: `${watch.symbol || "Token"} has completed its pullback and is ready for entry.`,
      };

    case "SETUP_INVALIDATED":
      return {
        type: "warning",
        title: "❌ Setup Invalidated",
        message: `${watch.symbol || "Token"} is no longer a valid trade setup.`,
      };

    case "BREAKOUT_FAILED":
      return {
        type: "warning",
        title: "⚠️ Breakout Failed",
        message: `${watch.symbol || "Token"} failed to confirm its breakout.`,
      };

    case "PULLBACK_FAILED":
      return {
        type: "warning",
        title: "⚠️ Pullback Failed",
        message: `${watch.symbol || "Token"} failed to complete its pullback.`,
      };

    default:
      return null;
  }
}

// =====================================================
// BUILD TELEGRAM CHANNEL MESSAGE
// =====================================================

function buildTelegramChannelMessage(watch, result, payload) {
  return `
${payload.title}

🪙 <b>Token:</b> ${watch.symbol || "Unknown"}

📊 <b>Event:</b> ${result.event}

⏮ <b>Previous:</b> ${result.previousAction ?? "-"}

▶️ <b>Current:</b> ${result.currentAction ?? "-"}

${payload.message}

🤖 <i>Generated by Autoswaps AI Chart Monitor</i>
`;
}

// =====================================================
// NOTIFY CHART WATCH
// =====================================================

export async function notifyChartWatch(watch, result) {
  if (!watch || !result) return;

  const payload = buildNotification(result, watch);

  if (!payload) return;

  // ===================================================
  // SYSTEM WATCH
  // ===================================================

  if (watch.watchType === "SYSTEM") {
    const SYSTEM_CHANNEL_ID = "-1002749359178";

    // -----------------------------------------------
    // DASHBOARD — APPROVED SUBSCRIBERS
    // -----------------------------------------------

    const users = await User.find({
      subscribedChannels: {
        $elemMatch: {
          channelId: SYSTEM_CHANNEL_ID,
          enabled: true,
          status: "approved",
        },
      },
    })
      .select("walletAddress")
      .lean();

    console.log(
      "📢 SYSTEM CHART NOTIFICATION — subscribers",
      {
        channelId: SYSTEM_CHANNEL_ID,
        subscriberCount: users.length,
        watchId: watch._id,
        symbol: watch.symbol,
        event: result.event,
      }
    );

    for (const user of users) {
      if (!user.walletAddress) continue;

      await createNotification({
        walletAddress: user.walletAddress,
        type: payload.type,
        title: payload.title,
        message: payload.message,
        data: {
          watchId: watch._id,
          tokenMint: watch.mintAddress,
          tokenSymbol: watch.symbol,
          previousAction: result.previousAction,
          currentAction: result.currentAction,
          event: result.event,
          channelId: SYSTEM_CHANNEL_ID,
        },
      });
    }

    // -----------------------------------------------
    // TELEGRAM CHANNEL
    // -----------------------------------------------

    try {
      const telegramMessage =
        buildTelegramChannelMessage(
          watch,
          result,
          payload
        );

      await bot.telegram.sendMessage(
        SYSTEM_CHANNEL_ID,
        telegramMessage,
        {
          parse_mode: "HTML",
        }
      );

      console.log(
        "📨 SYSTEM CHART NOTIFICATION — Telegram channel sent",
        {
          channelId: SYSTEM_CHANNEL_ID,
          watchId: watch._id,
          symbol: watch.symbol,
          event: result.event,
        }
      );
    } catch (telegramError) {
      console.error(
        "❌ SYSTEM CHART NOTIFICATION — Telegram channel failed:",
        telegramError?.message || telegramError
      );
    }

    return;
  }

  // ===================================================
  // USER WATCH
  // ===================================================

  if (!watch.walletAddress) {
    console.warn(
      "⚠️ USER CHART NOTIFICATION — missing walletAddress",
      {
        watchId: watch._id,
        symbol: watch.symbol,
        event: result.event,
      }
    );

    return;
  }

  await createNotification({
    walletAddress: watch.walletAddress,
    type: payload.type,
    title: payload.title,
    message: payload.message,
    data: {
      watchId: watch._id,
      tokenMint: watch.mintAddress,
      tokenSymbol: watch.symbol,
      previousAction: result.previousAction,
      currentAction: result.currentAction,
      event: result.event,
    },
  });
}