import User from "../../models/User.js";
import { getTelegramBot } from "./telegramBotService.js";

// =====================================================
// SEND TELEGRAM CHART ALERT
// =====================================================

export async function notifyTelegramChartWatch(
  watch,
  result
) {
  try {
    // ============================================
    // Validate watch
    // ============================================

    if (!watch?.walletAddress) {
      return;
    }

    // ============================================
    // Telegram Bot
    // ============================================

    const bot = getTelegramBot();

    if (!bot) {
      console.warn(
        "⚠️ Telegram Bot has not been initialized."
      );
      return;
    }

    // ============================================
    // Find user
    // ============================================

    const user = await User.findOne({
      walletAddress: watch.walletAddress,
    }).lean();

    if (!user) {
      return;
    }

    // ============================================
    // Telegram not linked
    // ============================================

    if (!user.telegram?.userId) {
      return;
    }

    // ============================================
    // Build message
    // ============================================

    const message = buildTelegramMessage(
      watch,
      result
    );

    // ============================================
    // Send message
    // ============================================

    await bot.telegram.sendMessage(
      user.telegram.userId,
      message,
      {
        parse_mode: "HTML",
      }
    );

    console.log(
      `📲 Chart alert sent to Telegram user ${user.telegram.userId}`
    );

  } catch (err) {

    console.error(
      "❌ Telegram chart notification failed:",
      err.message
    );

  }
}

// =====================================================
// FORMAT TELEGRAM MESSAGE
// =====================================================

function buildTelegramMessage(
  watch,
  result
) {

  const analysis =
    result.analysis || {};

  const symbol =
    watch.tokenSymbol || "Unknown";

  const forecast =
    watch.forecastScore ?? "-";

  return `
📈 <b>Chart Watch Update</b>

🪙 <b>Token:</b> ${symbol}

📊 <b>Event:</b> ${result.event}

⏮ <b>Previous:</b> ${result.previousAction}

▶️ <b>Current:</b> ${result.currentAction}

🎯 <b>Forecast Score:</b> ${forecast}

🔥 <b>Confidence:</b> ${analysis.confidence ?? "-"}

💰 <b>Entry Zone:</b>
${analysis.entryMin ?? "-"} - ${analysis.entryMax ?? "-"}

🎯 <b>Take Profit:</b>
${analysis.takeProfitLevel ?? "-"}

🛑 <b>Invalidation:</b>
${analysis.invalidationLevel ?? "-"}

📌 <b>Recommended Action:</b>
${analysis.action ?? "-"}

🤖 <i>Generated by Autoswaps AI Chart Monitor</i>
`;

}