// src/context/ai/AIActions.js

export const AI_ACTIONS = Object.freeze({
  UPDATE_SYSTEM: "UPDATE_SYSTEM",

  UPDATE_PORTFOLIO: "UPDATE_PORTFOLIO",

  UPDATE_MARKET: "UPDATE_MARKET",

  UPDATE_PIPELINE: "UPDATE_PIPELINE",

  UPDATE_POSITION_METRICS: "UPDATE_POSITION_METRICS",

  UPDATE_ANALYSIS: "UPDATE_ANALYSIS",

  UPDATE_DIAGNOSTICS: "UPDATE_DIAGNOSTICS",

  UPDATE_LEARNING: "UPDATE_LEARNING",

  UPDATE_AI_STATE: "UPDATE_AI_STATE",

  ADD_ACTIVITY: "ADD_ACTIVITY",

  CLEAR_ACTIVITY: "CLEAR_ACTIVITY",

  RESET_AI: "RESET_AI",
});